language: ruby

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile

sudo: false

script: 'bundle exec rake'
